### ISSUE TITLE
Fold-out 화면에서 룰렛이 잘리는 문제 

### ISSUE THREAD

**Issue by M1nseoPark** [JhDroid/android-roulette-wheel-view#1]
갤럭시 폴드에서 룰렛이 잘리는 문제가 발생합니다

![Screenshot_20230903_222923](https://github.com/JhDroid/android-roulette-wheel-view/assets/80569061/83a1a76b-b827-4b8f-8109-7e3f1a46cb81)

**Comment by JhDroid** [comment]
안녕하세요 제보 감사합니다 확인해볼게요!!

**Comment by JhDroid** [comment]
![image](https://github.com/JhDroid/android-roulette-wheel-view/assets/52662641/f0a9ee0f-991d-4b90-acc5-29123eaa0e9a)

오류 수정해서 다시 올렸습니다! (라이브러리 버전 : v1.0.3)

수정하면서 targetSdk 33 적용하고 gradle 정리 조금 했는데 
테스트 했을 땐 문제 없었는데 동일한 오류가 발생하거나 다른 오류 발생하면 문의 부탁드립니다 :)
